version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups/
    env_file: ./env/.env
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - 8006:8000
    volumes:
      - ./backend:/backend/
    depends_on:
      - db
    env_file: ./env/.env
    links:
      - db:db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - 8007:3000
    env_file: ./env/.env
    restart: unless-stopped

volumes:
    postgres_data:

