# Generated by Django 4.2 on 2023-07-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicla_plus', '0002_company_location_company_phone_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.PositiveBigIntegerField(),
        ),
    ]
