# Generated by Django 4.2 on 2023-07-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicla_plus', '0003_alter_company_cnpj_alter_person_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
