# Generated by Django 4.2 on 2023-08-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicla_plus', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='hidden',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('og', 'Ongoing'), ('de', 'Delivered'), ('ca', 'Canceled by advertiser'), ('cs', 'Canceled by supplier'), ('cm', 'Canceled by moderation')], default='og', max_length=2),
            preserve_default=False,
        ),
    ]
