# Generated by Django 4.2 on 2023-08-22 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicla_plus', '0005_advertisement_hidden_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 28, 28, 114191)),
        ),
    ]
