# Generated by Django 4.2 on 2023-08-23 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicla_plus', '0007_advertisement_is_deleted_transaction_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 17, 5, 20, 215380)),
        ),
    ]
