# Generated by Django 4.2 on 2023-08-23 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicla_plus', '0008_advertisement_is_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 21, 51, 20, 236811)),
        ),
    ]
